src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(['email'], message: 'Cette adresse email est déjà utilisée.')]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 32)]
    #[Assert\Length(min: 2, max: 32, minMessage: 'Votre prénom doit avoir minimum {{ limit }} caractères de long', maxMessage: 'Votre prénom doit avoir maximum {{ limit }} caractères de long')]
    private ?string $firstname = null;

    #[ORM\Column(length: 32)]
    #[Assert\Length(min: 2, max: 32, minMessage: 'Votre nom doit avoir minimum  {{ limit }} caractères de long', maxMessage: 'Votre nom doit avoir maximum {{ limit }} caractères de long')]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    #[Assert\Email(message: 'L\'adresse {{ value }} n\'est pas une adresse email valide.')]
    private ?string $email = null;

    #[ORM\Column(length: 32)]
    private ?string $contract_type = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $employement_date = null;

    /**
     * @var Collection<int, Task>
     */
    #[ORM\OneToMany(targetEntity: Task::class, mappedBy: 'user')]
    private Collection $tasks;

    /**
     * @var Collection<int, Project>
     */
    #[ORM\ManyToMany(targetEntity: Project::class, mappedBy: 'users')]
    private Collection $projects;

    /**
     * @var Collection<int, Project>
     */

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->projects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getInitials(): string
    {
        return strtoupper($this->firstname[0] . $this->lastname[0]);
    }

    public function getFullName(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getContractType(): ?string
    {
        return $this->contract_type;
    }

    public function setContractType(string $contract_type): static
    {
        $this->contract_type = $contract_type;

        return $this;
    }

    public function getEmployementDate(): ?\DateTimeInterface
    {
        return $this->employement_date;
    }

    public function setEmployementDate(\DateTimeInterface $employement_date): static
    {
        $this->employement_date = $employement_date;

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): static
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setUser($this);
        }

        return $this;
    }

    public function removeTask(Task $task): static
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getUser() === $this) {
                $task->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): static
    {
        dd("AddProject dans user");
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->addUser($this);
        }

        return $this;
    }

    public function removeProject(Project $project): static
    {
        dd("RemoveProject dans user");
        if ($this->projects->removeElement($project)) {
            dd("RemoveProject dans user");

            $project->removeUser($this);
        }

        return $this;
    }


}

src/Controller/TeamController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class TeamController extends AbstractController
{
    #[Route('/team', name: 'team')]
    public function index(UserRepository $userRepository): Response
    {
        $team = $userRepository->findAll();
        return $this->render('team/index.html.twig', [
            'controller_name' => 'TeamController',
            'titlePage' => 'Équipe',
            'team' => $team
        ]);

    }

    #[Route('/team/edit/{id}', name: 'edit_member')]
    public function editMember(EntityManagerInterface $entityUserManager, Request $request, User $user = null): Response
    {
        if (!$user) {
            throw $this->createNotFoundException('User not found');
        }
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityUserManager->flush();
            return $this->redirectToRoute('team');
        }

        return $this->render('/team/form.html.twig', [
            'controller_name' => 'EditMemberController',
            'titlePage' => $user->getFullName(),
            'titleBlock' => 'Modifier un membre',
            'user' => $user,
            'form' => $form
        ]);
    }

    #[Route('/team/member/delete/{id}', name: 'deleteMember')]
    public function deleteMember(EntityManagerInterface $entityUserManager, User $user = null): Response
    {
        if (!$user) {
            throw $this->createNotFoundException('User not found');
        }
        $entityUserManager->remove($user);
        $entityUserManager->flush();
        return $this->redirectToRoute('team');
    }

}

templates/team/form.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ titleBlock }}{% endblock %}

{% block body %}

        {{ form_start(form) }}
        {{ form_row(form.lastname) }}
        {{ form_row(form.firstname) }}
        {{ form_row(form.email) }}
        <div class="form-flex">
            {{ form_row(form.employement_date) }}
            {{ form_row(form.contract_type) }}
        </div>

        {{ form_end(form) }}


{% endblock %}

templates/team/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des employés{% endblock %}

{% block body %}
    <table id="team-container">
        <thead>
        <tr>
            <th>Prénom, Nom</th>
            <th>Statut</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for member in team %}
            <tr>
                <td>
                    <div class="employee-infos">
                        <div class="employee-avatar">
                            {{ member.getInitials() }}
                        </div>
                        <div class="employee-coords">
                            <strong>{{ member.firstname ~ " " ~ member.lastname}}</strong>
                            <span>{{ member.email }}</span>
                        </div>
                    </div>
                </td>
                <td>{{ member.contractType }}</td>
                <td>
                    <a class="button button-edit-team" href="{{ path('edit_member',{id:member.id}) }}">
                        Éditer
                    </a>
                    <a class="delete-team" href="team/member/delete/{{ member.id }}">
                        Supprimer
                    </a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}